# -*- coding: utf-8 -*-
"""sba2020.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LHyKTW8SZ7xfaFSQAaZwubmpeEW92J4W

## Cara simpan: klik `file` -> `Download .py`. kemudian upload ke netacad di soal anda. 
**NOTE: SEBELUM ANDA SUBMIT SILAKAN DIJALANKAN TERLEBIH DAHULU APAKAH SCRIPT/KODE ANDA BEBAS DARI ERROR ATAU TIDAK**.
"""

'''
namafile: sba.py
Lembar kerja/script Latihan SBA
'''
# >>>>>>LEMBAR KERJA>>>>>>>>>
# lembar ini hanya berisi pendefinisian fungsi dan class saja
 
#email netacad
email = 'dayangputri1@gmail.com'
 
# >>>>>>Soal 1
def fungsiIO():
  mas_angka=(input("Masukkan angka dipisahkan spasi : \n").split())
  ur=list(map(int,mas_angka))
  urut=sorted(ur)
  for i in urut:
    print("*"*i)
  
  pass
  # Mulai kode anda dari sini
 
# >>>>>>Akhir Soal 1 
 
# >>>>>>Soal 2
def caseShopia(txt):
  lis=[]
  for letter in txt:
    if letter.islower():
      a = letter.upper()
      lis.append(a)
    elif letter.isupper():
      b=letter.lower()
      lis.append(b)
    else :
      lis.append('')
  return ''.join(lis).strip('_')
  pass
  # Mulai kode anda dari sini
  
# >>>>>>Akhir Soal 2 
 
 # Jangan diubah biarkan seperti ini
dcur2idr = {'USD': 14425, 'EUR': 16225, 'AUD': 9925, 'CAD': 10500, 
             'GBP': 17800, 'CHF': 15200, 'SGD': 10375, 'HKD': 1775, 
             'JPY': 132500, 'MYR': 3250, 'SAR': 3500, 'WON': 10750, 
             'IDR': 1}
 
# >>>>>> Soal 3 
def usd2eur(usd):
  hasil_konv= usd*(dcur2idr["USD"]/dcur2idr["EUR"])
  return hasil_konv
  pass
  # Mulai kode anda dari sini
 
# >>>>>>Akhir Soal 3 
 
 
# >>>>>>Soal 4 
class MoneyChanger:
  def __init__(self,dcurrency,base='IDR',percent=2):
    self.dcurrency= dcurrency
    self.base = base
    self.percent= percent
    pass
    # Mulai kode anda dari sini
  def selling_price(self,nominal,curr):
    pass
    # Mulai kode anda dari sini
    harga_jualas= nominal*((self.dcurrency[curr])/(self.dcurrency[self.base]))
    harga_jual = harga_jualas+ (harga_jualas*self.percent/100)
    return harga_jual
 
  def buying_price(self,nominal,curr):
    pass
    # Mulai kode anda dari sini
    harga_belias= nominal*(self.dcurrency[self.base]/self.dcurrency[curr])
    harga_beli= harga_belias-(harga_belias*self.percent/100)
    return harga_beli
 
  def change_base(self,new_base):
    pass
    # Mulai kode anda dari sini
    self.base = new_base

 
 
# >>>>>>Akhir Soal 4 
 
# >>>>>>AKHIR LEMBAR KERJA>>>>>>>>>
 
 
 
# KODE DI BAWAH INI UNTUK TESTING
# ANDA BOLEH MEMBUANG SEMUA KODE DI SAAT SUBMISI KE NETACAD
 
def main():
  pass
  # >>>>>TEST DI SINI>>>>>>
  # gunakan BLOCK MAIN ini untuk mengetes
  # untuk pengetesan kode hanya boleh di bagian sini
  # silakan test sesuka hati di sini
 
  #############################################
  # uncomment script di bawah ini untuk testing
  #############################################
  
  # print('test soal 1')
  # fungsiIO() # contoh input: 7 4 5 2 1 3
 
  # print('test soal 2')
  # print(caseShopia('thXGth876%^$LMn.'))
 
  # print('test soal 3')
  # print(usd2eur(100))  # mengubah 100 USD ke EUR
 
  # print('test soal 4')
  # mc = MoneyChanger(dcur2idr,base='EUR') # object mc dengan base EUR
  # print('base', mc.base)
  # print(mc.selling_price(100,'USD')) # nilai jual 100 USD ke EUR (Base)
  # print(mc.buying_price(100,'USD')) # nilai beli 100 USD ke EUR (Base)
  
  # mc.change_base('IDR') # Ganti Base object mc ke IDR
  # print('base', mc.base)
  # print(mc.selling_price(100,'USD')) # nilai jual 100 USD ke IDR (Base)
  # print(mc.buying_price(100,'USD'))  # nilai beli 100 USD ke IDR (Base)
 
  # >>>>>AKHIR TEST DI SINI>>>>>>
 
if __name__ == '__main__':
  main()
